version: "3"
services:
  postgres:
    image: postgres
    container_name: super_four_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=superfourdb
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data