INSERT INTO vegetables(NAME, CATEGORY) VALUES
                                                       ('Anghinare', 'legume'),
                                                       ('Broccoli', 'legume'),
                                                       ('Conopidă', 'legume'),
                                                       ('Andivă sau cicoare de grădină', 'legume'),
                                                       ('Cimbru', 'legume'),
                                                       ('Creson', 'legume'),
                                                       ('Lăptucă', 'legume'),
                                                       ('Leuștean', 'legume'),
                                                       ('Lobodă', 'legume'),
                                                       ('Măcriș', 'legume'),
                                                       ('Mărar', 'legume'),
                                                       ('Pătrunjel', 'legume'),
                                                       ('Tarhon', 'legume'),
                                                       ('Salată', 'legume'),
                                                       ('Spanac', 'legume'),
                                                       ('Ștevie', 'legume'),
                                                       ('Varză', 'legume'),
                                                       ('Varză de Bruxelles', 'legume'),
                                                       ('Ardei', 'legume'),
                                                       ('Bamă', 'legume'),
                                                       ('Castravete', 'legume'),
                                                       ('Dovleac', 'legume'),
                                                       ('Dovlecel', 'legume'),
                                                       ('Pepene verde', 'legume'),
                                                       ('Roșie', 'legume'),
                                                       ('Vânătă', 'legume'),
                                                       ('Bob', 'legume'),
                                                       ('Fasole', 'legume'),
                                                       ('Linte', 'legume'),
                                                       ('Mazăre', 'legume'),
                                                       ('Năut', 'legume'),
                                                       ('Soia', 'legume'),
                                                       ('Cardon', 'legume'),
                                                       ('Cartof', 'legume'),
                                                       ('Cartof dulce', 'legume'),
                                                       ('Ceapă', 'legume'),
                                                       ('Ghimbir', 'legume'),
                                                       ('Gulie', 'legume'),
                                                       ('Hașmă', 'legume'),
                                                       ('Praz', 'legume'),
                                                       ('Revent sau rubarbă', 'legume'),
                                                       ('Sparanghel', 'legume'),
                                                       ('Usturoi', 'legume'),
                                                       ('Hrean', 'legume'),
                                                       ('Morcov', 'legume'),
                                                       ('Păstârnac', 'legume'),
                                                       ('Ridiche', 'legume'),
                                                       ('Ridiche neagră', 'legume'),
                                                       ('Scorțoneră', 'legume'),
                                                       ('Sfeclă', 'legume'),
                                                       ('Țelină', 'legume'),
                                                       ('Abiu', 'fructe'),
                                                       ('Acerola', 'fructe'),
                                                       ('Achenă', 'fructe'),
                                                       ('Afină', 'fructe'),
                                                       ('Agrișă', 'fructe'),
                                                       ('Agrume', 'fructe'),
                                                       ('Alună americană', 'fructe'),
                                                       ('Alună de pământ', 'fructe'),
                                                       ('Ananas', 'fructe'),
                                                       ('Avocado', 'fructe'),
                                                       ('Banană', 'fructe'),
                                                       ('Caisă', 'fructe'),
                                                       ('Cantalup', 'fructe'),
                                                       ('Carambola', 'fructe'),
                                                       ('Căpșună', 'fructe'),
                                                       ('Cireașă', 'fructe'),
                                                       ('Coacăză', 'fructe'),
                                                       ('Coconar', 'fructe'),
                                                       ('Corcodușă', 'fructe'),
                                                       ('Curmală', 'fructe'),
                                                       ('Dudă', 'fructe'),
                                                       ('Durian', 'fructe'),
                                                       ('Fistic', 'fructe'),
                                                       ('Fragă', 'fructe'),
                                                       ('Fructe citrice', 'fructe'),
                                                       ('Gutuie', 'fructe'),
                                                       ('Jujubă', 'fructe'),
                                                       ('Kaki', 'fructe'),
                                                       ('Kiwi', 'fructe'),
                                                       ('Lămâie', 'fructe'),
                                                       ('Mandarină', 'fructe'),
                                                       ('Mango', 'fructe'),
                                                       ('Măr', 'fructe'),
                                                       ('Măslină', 'fructe'),
                                                       ('Merișor', 'fructe'),
                                                       ('Migdală', 'fructe'),
                                                       ('Mură', 'fructe'),
                                                       ('Nectarină', 'fructe'),
                                                       ('Nucă', 'fructe'),
                                                       ('Nucă de cocos', 'fructe'),
                                                       ('Nucșoară', 'fructe'),
                                                       ('Olivă', 'fructe'),
                                                       ('Papaia', 'fructe'),
                                                       ('Pară', 'fructe'),
                                                       ('Pepene', 'fructe'),
                                                       ('Pepene galben', 'fructe'),
                                                       ('Piersică', 'fructe'),
                                                       ('Pomișoară', 'fructe'),
                                                       ('Portocală', 'fructe'),
                                                       ('Prună', 'fructe'),
                                                       ('Rodie', 'fructe'),
                                                       ('Smochină', 'fructe'),
                                                       ('Strugure', 'fructe'),
                                                       ('Strugurii-ursului', 'fructe'),
                                                       ('Tangerină', 'fructe'),
                                                       ('Tărtăcuță', 'fructe'),
                                                       ('Vișină', 'fructe'),
                                                       ('Zarzără', 'fructe'),
                                                       ('Zmeură', 'fructe'),
                                                       ('Alac', 'cereale'),
                                                       ('Amaranth', 'cereale'),
                                                       ('Avena', 'cereale'),
                                                       ('Grâu', 'cereale'),
                                                       ('Hrișcă', 'cereale'),
                                                       ('Mei', 'cereale'),
                                                       ('Orez', 'cereale'),
                                                       ('Orz', 'cereale'),
                                                       ('Orzoaică', 'cereale'),
                                                       ('Ovăz', 'cereale'),
                                                       ('Porumb', 'cereale'),
                                                       ('Secară', 'cereale'),
                                                       ('Sorg', 'cereale'),
                                                       ('Terci', 'cereale'),
                                                       ('Triticale', 'cereale')